# This class is responsible for appending metadata to an image that is generated by stable diffusion
# It takes an image path on instantiation and provides an interface to read/write the image metadata
from libxmp import XMPFiles, consts

class StableMetaData():

    # Initialise against an image
    def __init__(self, img_path):
        self.img_path = img_path
        self.xmpfile = XMPFiles( file_path=img_path, open_forupdate=True )
        self.xmp = self.xmpfile.get_xmp()

    def addMetaData(self, data_dict):
        for key, value in data_dict.items():
            self.xmp.set_property(consts.XMP_NS_DC, f"stableui-{key}", value)
    
    def readMetaData(self, key):
        return self.xmp.get_property(consts.XMP_NS_DC, key )

    # Save modified metadata back to file
    def save(self):
        if not self.xmpfile.can_put_xmp(self.xmp):
            print("Invalid XMP data, unable to save to file")
            return
        self.xmpfile.put_xmp(self.xmp)